### ISSUE TITLE
New plugin:  set consul keys on container start

### ISSUE THREAD

**Issue by bryanlarsen** [progrium/docker-plugins#3]
https://github.com/bryanlarsen/docker-consulkv-plugin

I'd like feedback, especially on the interface.   It would be nice if SERVICE_KEY becomes Docker convention the same way that SERVICE_NAME and SERVICE_ID have.  So let's get the name and interface right before it does.

Once you're happy with the interface, what should we do next?   I could send a PR to put a link in your README, or put the plugin right in your repo....

**Comment by progrium** [comment]
Looks good. My initial thoughts are the interface is still too complicated. How many keys do you think will often be set with this? What are some of the actual use cases that led you to make it?

I think we can simplify in a number of ways, while correcting some more aesthetic issues as well. 

First, although `:` is an invalid character in var names, this is only because it cannot be referenced using colon. You can still set variables with colon. In the current prototype, Docker clustering takes advantage of this. Because we don't use this in the container, but instead only by inspecting, we can break the rules a little bit. 

I bring this up because in your examples you set keys with lowercase names. I'm sure this is quite common, but the naming for that becomes quite ugly because of its internal inconsistency (`KEY_foo`). Instead, you could use colon as a harder separator that makes the case change feel more natural: `KEY:foo`.

Also, I know to be aligned with registrator semantics you use KEY to be more declarative. But let's be honest, this is really an imperative directive. This probably isn't meta-data as much as it is just a way to encode the action of setting a key, although given use cases I could be wrong. For this reason, we could use SET instead of KEY. Maybe to be more specific and obvious, we can more clearly communicate this is a "set" in our "config store" with maybe CONFIG_SET, though that might be confusing. Perhaps KV_SET would be a little more obvious and shorter. Now we have:

`KV_SET:foo=bar`

I think we can use the same reasoning behind `:` to collapse the KEY_DEFAULT case into KEY by adding a `?` "operator" to the end of the name. So assigning when not set looks like this:

`KV_SET:foo?=bar`

Perhaps SERVICE_KEY can be eliminated by making it part of prefix. Depending on actual use cases, maybe you only want scoped keys. How often do you have scoped (service) and unscoped (non-service) keys together? Directly under the same prefix?

Otherwise, maybe we can just generalize the concept and use naming that reads better given the framework we've set up:

`KV_SCOPED_SET:foo=bar`
or 
`KV_LOCAL_SET:foo=bar`

And the `?` operator would work the same. 

Anyway, just a braindump/brainstorm on how you might be able to simplify the interface, making it a little more general (so an etcd plugin could use it as well, the semantics are the same ... kv), and improve the aesthetic. 

Maybe if we merge it in as an official plugin, we'd call it `kv-consul`. You can imagine also maybe a `KV_DELETE` operation. And the same interface/semantics could work with a `kv-etcd` plugin.

**Comment by bryanlarsen** [comment]
"What are some of the actual use cases that led you to make it?"

Using consul-template with registrator to write nginx config files, I needed more than IP Address and Port.

```
KV_SET:foo=bar
KV_SET:foo?=bar
```

Awesome.   Exactly the feedback I was looking for.  Love it.

"Depending on actual use cases, maybe you only want scoped keys"

Yup, that's all I need so far.   The unscoped is there because I did that first and figured it was useful enough to maintain rather than rip out.

```
KV_SCOPED_SET:foo=bar
KV_LOCAL_SET:foo=bar
```

These seem to imply to me that there's a way to set the scope to something other than service-name/service-id/.   If you can suggest such a mechanism, then I'm cool with one of them.   Otherwise, I think I prefer:

```
KV_SERVICE_SET:foo=bar
```

"Maybe if we merge it in as an official plugin, we'd call it kv-consul"

I'll rename my repo now.  It's less confusing if the names match, and renaming is something that becomes difficult after time has passed.

**Comment by progrium** [comment]
Yeah, with regards to scoped/service, I thought you could either templatize the prefix config (which should probably be renamed to `KV_CONSUL_*`) like `KV_CONSUL_PREFIX=\$SERVICE_NAME/\$SERVICE_ID` or something like that. Or maybe it a separate config for "scope" ... but I figure since you already have prefix, you'd use that. Though this limits the usage of the plugin for all containers and uses to being scoped. 

Anyway, still not the most elegant, but something like that could be done. I just didn't like "service" being a first-class citizen of key-value semantics. Seems weird. Also "service set" can read too easily as a set of services.

**Comment by bryanlarsen** [comment]
I think we're close.   I'll play with it a bit.   We might have to iterate a bit on that until we get something that smells right.

**Comment by bryanlarsen** [comment]
How about `KV_SERVICE_SCOPED_SET` and `KV_SERVICE_<port>_SCOPED_SET:`?   It's pretty verbose, but I think it otherwise answers both of our concerns.   It implies that we may eventually have other types of scopes.

**Comment by progrium** [comment]
Yeah, getting pretty long. I try to avoid name schemes that push 5 parts.
Maybe we can clean it up and decouple it more with something like
`KV_SET:SERVICE_<port>:foo`

On Fri, Nov 21, 2014 at 10:50 AM, Bryan Larsen notifications@github.com
wrote:

> How about KV_SERVICE_SCOPED_SET and KV_SERVICE_<port>_SCOPED_SET: It's
> pretty verbose, but I think it otherwise answers both of our concerns. It
> implies that we may eventually have other types of scopes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/progrium/docker-plugins/issues/3#issuecomment-64000301
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by bryanlarsen** [comment]
`KV_SET:SERVICE_<port>:foo` works for me.

**Comment by bryanlarsen** [comment]
`KV_SET:SERVICE:<port>:foo` results in simpler code.

**Comment by bryanlarsen** [comment]
@progrium:  I'm looking at revisiting the API.  The original use case was for consul-template:  `{{range service 'foo' }}` gives you access to the service id which then allows you to pull more information about the service out of the kv store.  As I'm building out, though, I find that I'm inverting the relationship, using the kv store to find a list of services.   This is partly because consul-template doesn't currently support listing services by tag, but I suspect it might even be useful if they add that ability.

Basically I'd find it useful to be able to scope by things other than service id, and to have dynamic information in the value of the key.   I'm thinking that rather than any sort of specific syntax, we should just support simple substitutions, like Docker does with $VAR.

So rather than `KV_SET:SERVICE_<port>:foo` we could have `KV_SET:prefix/#{service_<port>_id}/foo #{container_id}`, or something similar.  Thoughts?

The other thing that will have to be eventually addressed is the ability to cleanup on container stop.  We could make this explicit (suggestions for syntax?) or we could make it implicit:  if the line contains anything invalidated by the container stopping (container_id, service_id, etc.), then it should be removed on stop.   Thoughts?

**Comment by josegonzalez** [comment]
@bryanlarsen not sure if you're still working on this, but hit me up if you wanted to continue discussing. Sorry about the late reply, I'm working my way through updating this repo :)
